add `tweak()` operation
bitcoinjs/ecpair pull request #8
Opened 2022-06-07 15:07 UTC by motorina0

This is a follow up from this [deprecated PR](https://github.com/bitcoinjs/ecpair/pull/6#issuecomment-1143745140)

Add the `tweak(t: Buffer): ECPairInterface;` method to `ECPairInterface`

It can tweak a `keyPair` that has a `privateKey`, and also a keyPair where only the `publicKey` is present.

The unit tests use the `tapTweakHash()` function to create the tweak hash. This has several benefits:
 - a deterministic way to produces the hash
 - do not pollute the fixtures with the tweak value
 - could (manually) check against regtest that the tweak is fine

2022-06-07 15:20 UTC, brandonblack requested changes

2022-06-07 15:20 UTC, brandonblack commented on src/ecpair.js
> +    tweak(t) {
We should support both x-only and ordinary tweaking here, to avoid future pain. Don't care which is default.

2022-06-07 15:20 UTC, brandonblack commented on src/ecpair.js
> +          : ecc.privateNegate(this.privateKey);
```suggestion
      const hasOddY = this.publicKey[0] === 3 || this.publicKey[0] === 4 && this.publicKey[64] & 1 === 1;
      const privateKey = hasOddY ? ecc.privateNegate(this.privateKey) : this.privateKey;
```

2022-06-07 16:01 UTC, brandonblack commented on src/ecpair.js
> +    tweak(t) {
It would require code changes in more places than just here, so I didn't add one. Here, we'd do:
```
tweak(t, xOnly=true) {
  if (this.privateKey) return this.tweakFromPrivateKey(t, xOnly);
  return this.tweakFromPublicKey(t, xOnly);
}
```

Then, with my other suggestion, `tweakFromPrivateKey` line 154's would become:
`const privateKey = (hasOddY && xOnly) ? ecc.privateNegate(this.privateKey) : this.privateKey;`

and `tweakFromPublicKey` would get a clause like:
```
if (!xOnly) {
  const tweakedPublicKey = ecc.pointAddScalar(this.publicKey, t);
  return fromPublicKey(
    Buffer.from(tweakedPublicKey),
    { network: this.network, compressed: this.compressed },
  );
}
```

and finally, we'd add `pointAddScalar` to the `TinySecp256k1Interface`.

2022-06-07 19:59 UTC, motorina0 commented on src/ecpair.js
> +    tweak(t) {
What am I missing?
- `xOnly` refers to the public key (it means we do not know the parity of Y, it can be odd or even)
- currently for any instance of `ECPair` we **always** have the public key (and its parity)
- trying to create an instance of `ECPair` with a xOnly (32 bytes) publicKey would also affect the `[to|from]WIF()` methods
  - it is out of the scope of this PR to investigate if xOnly public keys can/should be serialized to/from WIF format
- passing `xOnly` to `tweak()` is redundant. It only tells us that the parity is present or not (which we already know from the publicKey value/length)

2022-06-07 19:59 UTC, motorina0 commented on src/ecpair.js
> +          : ecc.privateNegate(this.privateKey);
Done

2022-06-07 20:06 UTC, brandonblack commented on src/ecpair.js
> +    tweak(t) {
xOnly refers not to the public key contained in the `ECPair` being tweaked, but rather to the method of tweaking.

xOnly tweaking results in the same tweaked public key regardless of the parity of the original key.

ordinary tweaking results in different tweaked public keys depending on the parity of the original key.

xOnly tweaking is used in Bitcoin Taproot.

ordinary tweaking is what is performed as part of BIP32 derivation (etc).

ECPair as a building block should support both.

2022-06-08 07:03 UTC, junderw commented on ts_src/ecpair.ts
> +export interface XOnlyPointAddTweakResult {
We shouldn't export this, imo.

2022-06-08 07:04 UTC, junderw commented on src/ecpair.js
> +    tweak(t) {
Keep scope to taproot only for now. I understand the issue, but it can be added afterward using an optional flag.

2022-06-08 07:08 UTC, motorina0 commented on ts_src/ecpair.ts
> +export interface XOnlyPointAddTweakResult {
Fixed.

2022-06-08 14:12 UTC, brandonblack approved these changes

2022-06-12 09:32 UTC, junderw approved these changes

2022-06-12 09:32 UTC, merged

2022-06-12 09:33 UTC, junderw commented
I'll publish once bip32 is merged and we can publish together.

2022-09-26 06:47 UTC, motorina0 commented
> I'll publish once bip32 is merged and we can publish together.

`bip32` published